https://feedback.gpt.space/p/hott-mess-chodum01-links-in

curl \
  -H "Content-Type: application/json" \
  -d "{\"contents\":[{\"parts\":[{\"text\":\"Explain how AI works\"}]}]}" \
  -X POST "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent?key=YOUR_API_KEY"===AIzaSyBrLgEz2ag4WaiIE1_eB5AFTrHsH3DZP90

{
    "title": "Recording 11/25/2024 at 1:31:41 PM",
    "selectorAttribute": ">https://youtu.be/K-1gYb5sNmg",
    "steps": [
        {
            "type": "setViewport",
            "width": 295,
            "height": 647,
            "deviceScaleFactor": 1,
            "isMobile": false,
            "hasTouch": false,
            "isLandscape": false
        },
        {
            "type": "navigate",
            "url": "https://keep.google.com/u/0/#NOTE/1Wtl3OwEG0jCQPEiPXl4wo9SbjJBcU4gd2nty_MmAz19CG6nCDbP6dIWE5pXyPWk",
            "assertedEvents": [
                {
                    "type": "navigation",
                    "url": "https://keep.google.com/u/0/#NOTE/1Wtl3OwEG0jCQPEiPXl4wo9SbjJBcU4gd2nty_MmAz19CG6nCDbP6dIWE5pXyPWk",
                    "title": "Google Keep"
                }
            ]
        },
        {
            "type": "waitForElement",
            "selectors": [
                [
                    ".cls"
                ]
            ]
        }# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          <iframe width="560" height="315" src="https://www.youtube.com/embed/Aoz6hZrKBpE?si=Zwn4ekfYYfP-ySVb" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>< iframe width="560" height="315" src="https://www.github.com/Chodum91{ "ns": "yt", "el": "detailpage", "cpn": "Dql6S2BFwIb2yUoR",} "ver": 2, "cmt": "42.284", "fmt": "243", "fs": "0", "rt": "49.807", "euri": "", "lact": 1, "cl": "534545706", "mos": 0, "state": "8", "volume": 100, "cbrand": "google", "cbr": "Chrome", "cbrver": "113.0.0.0", "c": "WEB", "cver": "2.20230530.05.00", "cplayer": "UNIPLAYER", "cmodel": "chromebook", "cos": "CrOS", "cosver": "14541.0.0", "cplatform": "DESKTOP", "hl": "en_US", "cr": "CA", "len": "131.381", "fexp": "23983296,23986026,24004644,24007246,24080738,241 35310,24219382,24255165,24363113,24364789,243684 44,24368936,24415864,24433679,24437577,24439361,2 4451437,24532855,24550458,24550951,24556991,2455 8641,24559644,24691744,24698915,24699899,3932307 4,39323713", "afmt": "251", "muted": "0", "conn": "3", "docid": "_UXP2RABUDA", "ei": "r3Z4ZLSKsPZgwPeiKLoCQ", "plid": "AAX9DyEDq7rfkBNr", "referrer": "https://www.google.com/", "sdetail": "p:www.google.com/", "sourceid": "r", "of": "iSv_ZmrtQNZCzWrEG0t5Pg", "osid": "NjVjMjgxODU:AOeUNAb7G7uKdVCL_BUYy0ASwsdbgw68 SA", "vm": "CAMQARgBOjJBQ00wQ1loR2hKSk1MS1AzWlpZWTlCSE1 4Q2JJWGVXZm9XVnBRN0tnbHJlQVhNbFEtd2JgQVBta0t ETG50ZnNCdlZvODlBaGdGZ0thQnIwTHBZZzRmLUh1Wm UxYlpIUjBRNk1meVpFTHlNTjNRbTgzelBseVh2bDFuREs3a zVGLWN0Mlh0VVR5MjUzSF9JMTJ4Tlg3aAE", "vct": "42.284", "vd": "131.381", "vpl": "0.000-42.284", "vbu": "0.000-110.001", "vpa": "0", "vsk": "0", "ven": "0", "vpr": "1", "vrs": "4", "vns": "2", "vec": "null", "vemsg": "", "vvol": "1", "vdom": "1", "vsrc": "1", "vw": "402", "vh": "401", "lct": "42.135", "lsk": false, "lmf": false, "lbw": "439876.393", "lhd": "0.310", "lst": "1478.238", "laa": "itag_251_type_3_src_reslicegetRequestInfoForRange_seglva": "itag_243_type_3_src_reslicegetRequestInfoForRange_seg src_reslicegetRequestInfoForRange_seg_25_range_13876 76-1436786_time_128.0- 131.4_off_0_len_49111_end_1_eos_1", "lar": "itag_251_type_3_src_getRequestInfoForRange_segsrc_ge tRequestInfoForRange_seg_10_range_1278887- 1404265_time_100.0-110.0_off_0_len_125379_end_1", "lvr": "itag_243_type_3_src_getRequestInfoForRange_segsrc_ge tRequestInfoForRange_seg_25_range_1387676- 1436786_time_128.0- 131.4_off_0_len_49111_end_1_eos_1", "laq": "0", "lvq": "0", "lab": "0.000-110.001", "lvb": "0.000-131.360", "ismb": 25120000, "leader": 1, "relative_loudness": "-7.640", "optimal_format": "360p", "user_qual": 0, "release_version": "youtube.player.web_20230523_01_RC00", "debug_videoId": "_UXP2RABUDA", "0sz": "false", "op": "", "yof": "false", "dis": "", "gpu": "Mesa_Intel(R)_UHD_Graphics_(JSL)", "debug_playbackQuality": "medium", "debug_date": "Thu Jun 01 2023 07:45:56 GMT-0300 (Atlantic Daylight Time)" } - May 30, 2023

          echo test, and deploy your project.
